version: '3.8'

services:
  resource-monitor:
    build: .
    container_name: resource-monitor
    restart: unless-stopped
    # Required for accurate system metrics
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - TZ=${TZ:-UTC}
      # Telegram configuration
      # Leave TELEGRAM_TOKEN empty for console mode
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - CHAT_ID=${CHAT_ID:-}
      - INTERVAL_MINUTES=${INTERVAL_MINUTES:-60}
    # Command line arguments for the application
    command: >
      dotnet ResourceMonitorCli.dll ${TELEGRAM_TOKEN:+--telegram ${TELEGRAM_TOKEN}} ${TELEGRAM_TOKEN:+--chat ${CHAT_ID}} ${TELEGRAM_TOKEN:+--interval ${INTERVAL_MINUTES}}
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
